### ISSUE TITLE
Responsive design problems

### ISSUE THREAD

**Issue by kzmozkabadayi** [Trendyol/perfanalytics#60]

**Comment by ddenizakpinar** [comment]
@kzmozkabadayi I merged some fixes about this issue with my latest commits. There are still some opportunities to improve UI tho.

**Comment by kzmozkabadayi** [comment]
@ddenizakpinar god bless your hands kardo :) Can we go over it again when you have available time?

**Comment by k61b** [comment]
Shall we close Issue?
